### ISSUE TITLE
View metadata on 000040 causes browser into "Aw snap"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#662]
It might be just too long, but must be beyond 30 sec as we do get through on 000026 with slightly over 30 sec (see https://github.com/dandi/dandi-api-webshots/#000026)  but browser (when trying locally directly without webshots) does just say that Aw Snap eventually)

**Comment by yarikoptic** [comment]
<details>
<summary>probably the same for 000041</summary> 

```
2021-05-09T13:36:50-0400 [INFO    ] 000041 edit-metadata
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-api-webshots/tools/make_webshots.py", line 237, in <module>
    stats = process_dandiset(driver, ds)
  File "/home/yoh/proj/dandi/dandi-api-webshots/tools/make_webshots.py", line 150, in process_dandiset
    act()
  File "/home/yoh/proj/dandi/dandi-api-webshots/tools/make_webshots.py", line 112, in click_edit
    edit_button.click()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webelement.py", line 672, in _execute
    return self._parent.execute(command, params)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=88.0.4324.182)

```
</details>

**Comment by satra** [comment]
we should check validity of dandi metadata for all dandisets. in dandi cli, we need to turn models to contain all fields even if optional for base models, so that we can run through using model validation. i'll give this a shot later today.

**Comment by yarikoptic** [comment]
Regardless of the metadata validity, web ui must not just freeze IMHO.

**Comment by yarikoptic** [comment]
@waxlamp @mvandenburgh - do you see a way to establish some "watchdog" for a loading meditor, so if it fails to load e.g. in 20 seconds, it would time out and provide an error message to file an issue here? (could even prepopulate the body of the message via URL content with details on the browser and exact url)

**Comment by waxlamp** [comment]
It's a good question. Unfortunately, I am pretty sure the answer is "no", but maybe there is something out there I'm not aware of.

Are you finding long loading times still on a particular dandiset?

**Comment by yarikoptic** [comment]
> Are you finding long loading times still on a particular dandiset?

Not at the moment!  But I think to get this particular issue "Closed" fully, if there is an opportunity to ensure "must not freeze", that would be the way.  Thus decided to run an idea by you.

**Comment by mvandenburgh** [comment]
Well, there's still a ~10 second lag on https://gui.dandiarchive.org/#/dandiset/000026 (not as bad as the loading times we used to see, but still not acceptable from a UX standpoint I think)

**Comment by yarikoptic** [comment]
yeap, max time somehow consistent between deployed and staging instances ATM, it is 9 sec on https://github.com/dandi/dandi-api-webshots-staging#000032 .  Indeed not optimal UX but at least not halting the entire page (this issue) for minutes causing browser to announce the ultimate death ;)

**Comment by waxlamp** [comment]
I did a bit of profiling on 000026, and I see that the bulk of the slowdown time is spent in Vue's DOM/layout/etc. computations, specifically within a watcher. I didn't dive much deeper than that. @mvandenburgh, maybe you can do a bit more investigation here, play around with VJSF options, and maybe even ask VJSF for help in diagnosing what's going on here.
